### ISSUE TITLE
Cask

### ISSUE THREAD

**Issue by Zyst** [Atelier-Shiori/MAL-Library#6]
Are there any plans to create a cask for brew? Or is the appstore the only download vector.

This is fully a question not a request.

**Comment by chikorita157** [comment]
For it to be on cask, this repo at least needs 10 stars or more. That what the guidelines say. I will request it once it reaches that threshold.

You can download a limited copy here - https://malupdaterosx.ateliershiori.moe/downloadmallibrary.php . Manga support requires a donation key or downloading it from the App Store.
