### ISSUE TITLE
Just closes

### ISSUE THREAD

**Issue by Enuqt** [Atelier-Shiori/MAL-Library#9]
My MAL Library just closes up on opening it I had a older version installed updated it now it doesn't open anymore, what files do I need to delete to maybe reset cache if u need any more information feel free to write me.
Love ur work.
Kind regards,
Enu

**Comment by chikorita157** [comment]
To troubleshoot, right click the application. Open Contents > MacOS  and open MAL Library. Copy the terminal content. Crashlytics should pick up a crash if there is one on my end.

**Comment by Enuqt** [comment]
Last login: Tue Aug 15 21:23:29 on ttys000
ENU-MBP:~ enu$ /Applications/MAL\ Library.app/Contents/MacOS/MAL\ Library ; exit;
2017-08-17 15:28:01.987 MAL Library[36968:5306234] [Crashlytics] Version 3.8.4 (121)
2017-08-17 15:28:02.082 MAL Library[36968:5306247] [Crashlytics:Crash:Reports] Packaged report with id '04b2079a53b247af961225362032ed4c' for submission
2017-08-17 15:28:06.087 MAL Library[36968:5306234] -[__NSDictionaryI bytes]: unrecognized selector sent to instance 0x7f9036c3df60
Illegal instruction: 4
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...169 completed.

[Prozess beendet]

**Comment by chikorita157** [comment]
Try this build. Crashlytics indicated it's something with the periodic key check. I have the request class to handle the JSON parsing instead of doing it manually. 

[mallibrary-2.2.dmg.zip](https://github.com/Atelier-Shiori/MAL-Library/files/1231504/mallibrary-2.2.dmg.zip)

**Comment by Enuqt** [comment]
Working perfect now ! Thank you very much !
